#include "shared.h"

int main() {

    HKEY hKey;

    RegDeleteKeyEx(HKEY_CLASSES_ROOT, EASYATP_REG_PATH, KEY_WOW64_64KEY, 0);
    RegDeleteKeyEx(HKEY_LOCAL_MACHINE, EASYATPADDTOPATH_REG_COMMAND, KEY_WOW64_64KEY, 0);
    RegDeleteKeyEx(HKEY_LOCAL_MACHINE, EASYATPREMOVEFROMPATH_REG_COMMAND, KEY_WOW64_64KEY, 0);
    RegDeleteKeyEx(HKEY_LOCAL_MACHINE, EASYATPOPENPATHSETTINGS_REG_COMMAND, KEY_WOW64_64KEY, 0);
    RegDeleteKeyEx(HKEY_LOCAL_MACHINE, EASYATPADDTOPATH_REG_PATH, KEY_WOW64_64KEY, 0);
    RegDeleteKeyEx(HKEY_LOCAL_MACHINE, EASYATPREMOVEFROMPATH_REG_PATH, KEY_WOW64_64KEY, 0);
    RegDeleteKeyEx(HKEY_LOCAL_MACHINE, EASYATPOPENPATHSETTINGS_REG_PATH, KEY_WOW64_64KEY, 0);

    return 0;
}
